from src import db

class Oral_examination(db.Model):
    tooth_id = db.Column(db.Integer,primary_key=True)
    user_id = db.Column(db.Integer)
    tooth_location = db.Column(db.String(50))
    tooth_type = db.Column(db.String(50))
    caries_tired = db.Column(db.String(50))
    depth = db.Column(db.String(50))
    fill = db.Column(db.String(50))
    secondary = db.Column(db.String(50))
    color_of_caries = db.Column(db.String(50))
    flex_of_caries = db.Column(db.String(50))
    cold = db.Column(db.String(50))
    hot = db.Column(db.String(50))
    touch = db.Column(db.String(50))
    bite = db.Column(db.String(50))
    vitality_value_of_teeth = db.Column(db.String(50))
    gingival_hyperemia = db.Column(db.String(50))
    gingival_color = db.Column(db.String(50))
    tartar_up = db.Column(db.String(50))
    tartar_down = db.Column(db.String(50))
    bop = db.Column(db.String(50))
    periodontal_pocket_depth = db.Column(db.String(50))
    furcation = db.Column(db.String(50))
    location = db.Column(db.String(50))
    fistula = db.Column(db.String(50))
    overflow_pus = db.Column(db.String(50))
    mobility = db.Column(db.String(50))
    loss_caries_index_up = db.Column(db.String(50))
    loss_caries_surface_index_up = db.Column(db.String(50))
    development_of_the_situation = db.Column(db.String(50))
    relations_between_teeth = db.Column(db.String(50))
    is_teeth_crowd = db.Column(db.String(50))
    involution_teeth = db.Column(db.String(50))
    tooth_shape = db.Column(db.String(50))
    treatment = db.Column(db.String(50))
    orthodontic = db.Column(db.String(50))
    X_Ray_location = db.Column(db.String(50))
    X_Ray_depth = db.Column(db.String(50))
    X_Ray_fill_quality = db.Column(db.String(50))
    CT_shows = db.Column(db.String(300))
    piece = db.Column(db.String(300))

    def get_dict(self):
        dit = self.__dict__
        del dit['_sa_instance_state']
        return dit