import user_controller
import personal_history_controller
import tooth_location_controller
import illness_history_controller
import oral_examination_controller
import diagnose_controller
import difficulty_assessment_controller
import handle_controller